auction/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from .views import (
    auction_details,
    auctions,
    dashboard,
    home_page,
    login_page,
    create_auction_item_page,
    update_auction_item_page,
    posted_items_page,
    product_details_page,
)

urlpatterns = [
    path("", home_page, name="home"),
    path("login/", login_page, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("new-auction-item/", create_auction_item_page, name="create_auction_item"),
    path("my-items/", posted_items_page, name="my_items"),
    path("product/<int:pk>/", product_details_page, name="product_details"),
    path(
        "product/<int:pk>/edit/", update_auction_item_page, name="update_auction_item"
    ),
    # dashboard
    path("dashboard", dashboard, name="dashboard"),
    path("dashboard/auctions", auctions, name="auctions"),
    path("dashboard/auctions/<int:pk>/", auction_details, name="auction_details"),
]

core/models.py
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Max


class User(AbstractUser):
    email = models.EmailField(unique=True)


class AuctionProduct(models.Model):
    product_name = models.CharField(max_length=200)
    product_photo = models.ImageField(upload_to="products/")
    minimum_bid_price = models.DecimalField(max_digits=8, decimal_places=2)
    product_description = models.TextField()
    end_date = models.DateField()

    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    added_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="auction_products"
    )

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse("product_details", kwargs={"pk": self.pk})

    @property
    def get_top_bid(self):
        result = ProductBid.objects.filter(product=self).aggregate(Max("bid_price"))
        result = result.get("bid_price__max") or 0
        return result

    class Meta:
        ordering = ["-created_at"]


class ProductBid(models.Model):
    product = models.ForeignKey(
        AuctionProduct, on_delete=models.CASCADE, related_name="product_bid"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="product_bid")
    bid_price = models.DecimalField(max_digits=8, decimal_places=2)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

    class Meta:
        ordering = ["-created_at"]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% comment %} font awesome {% endcomment %}
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <title>{% block title %}{% endblock title %} AuctionApp</title>
  </head>
  <body>
    <header>
      {% include 'snippets/header.html' %}
    </header>

    <div class="container mt-4">
      {% comment %} messages {% endcomment %}
      {% if messages %}
      {% include 'snippets/messages.html' %}
      {% endif %}

      {% block body %}
      {% endblock body %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> {% endcomment %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/create_action_item.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card border-0 shadow">
            <div class="card-header">
                <h5>Add New Action Item</h5>
            </div>
            <div class="card-body">
                <form action="." method="POST" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-md-12 mb-2">
                            {{ form.product_name|as_crispy_field }}
                        </div>
                        <div class="col-md-6 mb-2">
                            {{ form.minimum_bid_price|as_crispy_field }}
                        </div>
                        <div class="col-md-6 mb-2">
                            {{ form.product_photo|as_crispy_field }}
                        </div>
                        <div class="col-md-12 mb-2">
                            {{ form.end_date|as_crispy_field }}
                        </div>
                        <div class="col-md-12 mb-2">
                            {{ form.product_description|as_crispy_field }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success w-100 mt-4">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/home.html
{% extends "base.html" %}

{% block body %}
<div class="row">
    <div class="d-flex justify-content-end mb-5 me-5">
        <a href="{% url 'create_auction_item' %}" class="btn btn-outline-success">
            <i class="fas fa-plus"></i> Item
        </a>
    </div>
    {% for product in products %}
    <div class="col-md-3">
        <div class="card border-0 shadow">
            <div class="card-body">
                <img class="icard-img-top img-fluid" src="{{product.product_photo.url}}" alt="{{ product.product_name }}">
                <h4 class="mt-4 text-center">{{ product.product_name }}</h4>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item text-secondary">Min Bid: {{ product.minimum_bid_price }}</li>
                    <li class="list-group-item text-secondary">End Date: {{ product.end_date }}</li>
                </ul>
                <div class="d-flex justify-content-center">
                    {% now "Y-m-d" as todays_date %}
                    {% if product.end_date|date:"Y-m-d" < todays_date %}
                    <a href="{{product.get_absolute_url}}" class="btn btn-danger btn-sm stretched-link">Expired</a>            </div>
                    {% elif product.added_by == request.user %}
                    <a href="{{product.get_absolute_url}}" class="btn btn-outline-secondary btn-sm stretched-link">View</a>            </div>
                    {% else %}
                    <a href="{{product.get_absolute_url}}" class="btn btn-outline-success btn-sm stretched-link">Bid Product</a>            </div>
                    {% endif %}
                </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock body %}

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block body %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card border-0">
            <div class="card-header">
                <h5>Login</h5>
            </div>
            <div class="card-body">
                <form action="." method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success w-100 mt-3">Sign in</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/my_posted_items.html
{% extends "base.html" %}

{% block body %}
<div class="row">
    <div class="d-flex justify-content-end mb-5 me-5">
        <a href="{% url 'create_auction_item' %}" class="btn btn-outline-success">
            <i class="fas fa-plus"></i> Item
        </a>
    </div>
    {% for product in products %}
    <div class="col-md-3">
        <div class="card border-0 shadow">
            <div class="card-body">
                <img class="icard-img-top img-fluid" src="{{product.product_photo.url}}" alt="{{ product.product_name }}">
                <h4 class="mt-4 text-center">{{ product.product_name }}</h4>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item text-secondary">Min Bid: {{ product.minimum_bid_price }}</li>
                    <li class="list-group-item text-secondary">End Date: {{ product.end_date }}</li>
                </ul>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock body %}

templates/product_details.html
{% extends "base.html" %}

{% block body %}
<div class="row">
    <div class="col-md-6">
        <img class="img-thumbnail" src="{{ product.product_photo.url }}" alt="{{ product.product_name }}">
    </div>
    <div class="col-md-6">
        {% if request.user == product.added_by %}
        <div class="d-flex justify-content-end">
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'update_auction_item' product.pk %}">
            <i class="fa fa-edit"></i> Edit
          </a>
        </div>
        {% endif %}

        <h4>{{ product.product_name|title }}</h4>
        <ul class="list-group">
            <li class="list-group-item text-secondary"><strong class="me-2">Min Bid Price:</strong> {{ product.minimum_bid_price }}</li>
            <li class="list-group-item text-secondary"><strong class="me-2">End Date:</strong> {{ product.end_date }}</li>
        </ul>
        <p class="mt-3">{{ product.product_description }}</p>

        {% if expired %}
        <div class="alert alert-danger" role="alert">
          This auction has expired!
        </div>
        {% endif %}
        <h4>Bid Now:</h4>
        
        <form action="." method="POST">
          {% csrf_token %}
          <div class="row">
            <div class="col">
              <div class="mb-2">
                <input {% if expired %}disabled{% endif %} value="{% if user_bid %}{{ user_bid.bid_price }}{% endif %}" type="number" step="0.01" id="id_bid_price" name="bid_price" class="form-control" required>
              </div>
            </div>
            <div class="col-md-4">
              <button class="btn btn-success w-100" {% if expired %}disabled{% endif %}>
                {% if user_bid %}Update Bid {% else %} Bid {% endif %}
              </button>
            </div>
          </div>
        </form>
    </div>
</div>

<div class="row mt-5">
    <h4>Biding Table</h4>
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">User</th>
                    <th scope="col">Bid</th>
                  </tr>
                </thead>
                <tbody>
                  {% for bid in product_bids %}
                  <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{bid.user}}</td>
                    <td>{{bid.bid_price}}</td>
                    <td>
                      {% if bid.bid_price == winner.bid_price__max %}
                      <div class="badge bg-success">Winner</div>
                      {% endif %}
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
</div>
{% endblock body %}